// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ad2f4f37-219c-447f-8e46-254db790792a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fQBfShs5D",
    "aws_user_pools_web_client_id": "3klbc4esvd6rdq6b6k68g4vq78",
    "oauth": {},
    "aws_user_files_s3_bucket": "growertoyou-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
